spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/otm-employee-dev?serverTimezone=UTC
    username: otm_user
    password: s3cr3t!=

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8088/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
